# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inazumaCSS_cloud.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import os
import random
import time
import re
import rsc_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        self.Nb_Cycle = 4
        self.Countdown = 15

        self.yourTeam = []
        self.offset = 0
        self.counter = 0
        self.Status = False
        self.selected_previous_option = "Formation"
        self.Team = {
            "RM": "Raimon",
            "OC": "Occulte",
            "WD": "Wild",
            "CT": "Cybertech",
            "OK": "Otaku",
            "RA": "Royal Academie",
            "SK": "Shuriken",
            "TA": "Terria",
            "KW": "Kirkwood",
            "ZS": "Zeus",
            "OI": "Onze d'Inazuma",
            "SS": "Street Sally's",
            "KF": "Inazuma Kids FC",
            "UB": "Umbrella",

            "ST": "Services Secrets",
            "AP": "Alpin",
            "CD": "Cloître Divin",
            "3C": "Super Triple C",
            "FS": "Fauxshore",
            "MT": "Mary Times",
            "TG": "Tempête des Gémeaux",
            "EP": "Epsilon",
            "NE": "Nouvel Epsilon",
            "NR": "Nouvelle Royal Academie",
            "PM": "Prominence",
            "DD": "Diamond Dust",
            "GS": "Genesis",
            "EN": "Empereurs Noirs",
            "RdG": "Robots de Garde",
            "FT": "Forest Team",
            "JI": "Jeunes Inazuma",

            "IJ": "Inazuma Japon",
            "NJ": "Neo Japon",
            "BW": "Big Waves",
            "LdD": "Lions du Désert",
            "DF": "Dragons de Feu",
            "KQ": "Knights of Queen",
            "TD": "Team D",
            "LE": "Les Empereurs",
            "LL": "Les Licornes",
            "OP": "Orphée",
            "RF": "Les Rois du Football",
            "TZ": "Team Zoolan",
            "LG": "Little Gigantes",
            "RG": "Rose Griffons",
            "TR": "Les Toreros Rouges",
            "BB": "Brocken Bogue",
            "CC": "The Cape Crusaders",
            "TO": "Team Ogre",
            "MC": "Sky Team",
            "DT": "Dark Team",
            "AN": "Anges Noirs",
            
            "AO": "l'Âge d'Or",
            "KFGO": "Inazuma KFC",
            "UMT": "Ultramégatétra",
            "RMGO": "Raimon GO",
            "RM R": "Raimon Reserve",
            "CN": "Chevaliers Noirs",
            "SR": "Surdoués",
            "VL": "Voie Lactée",
            "FTP": "Foi Toute-Puissante",
            "RAGO": "Royal Academy GO",
            "BP": "Baie des Pirates",
            "ML": "Mers Lunaires",
            "APGO": "Alpin GO",
            "KWGO": "Kirkwood GO",
            "CM": "Collège des Mirages",
            "CU": "Collège Universel",
            "MO": "Mont Olympe",
            "AdD": "Alliance du Dragon",
            "LME": "Lumière Éternelle",
            "OA": "Ombre Ancestral",
            "E0": "Équipe Zéro",
            "GdS": "Griffe du Sud",
            "CdN": "Croc du Nord",
            "RD": "Rage du Démon",


            "SHW": "Les Sherwinds",
            "PO": "Protocol Omega",
            "PO2": "Protocol Omega 2.0",
            "PO3": "Protocol Omega 3.0",
            "ZD": "Zanark Domination",
            "EX": "Excellence",
            "ZAN": "Zan",
            "GIH": "Gihl",
            "GAH": "Gahl",
            "RGN": "Ragna",
            "CS": "Chrono Storm",
            "BCB": "Bande du Cerf Blanc",
            "RS": "Robots de Surveillance",
            "SA": "Statues d'Argile",
            "IJE": "Inazuma Japon Évolution",
            "RdD": "Roses du Désespoir",
            "ES": "Enfants Sauvages",
            "TN": "Traqueurs Nocturnes",

            "IN": "Inazuma National",
            "DFGO": "Dragons de Feu (GO)",
            "BWGO": "Big Waves (GO)",
            "SBA": "Sabres Arides",
            "TT": "Tigres de Thaïlande",
            "LO": "Loups d'Ouzbékistan",
            "OT": "Onze Terrestre",
            "OS": "Onze de Silica",
            "ON": "Onze de Naiadi",
            "OM": "Onze de Magmavia",
            "OF": "Onze de Fertilia",
            "FM": "Falam Medius",
            "AI": "Armada Ixar",
            "BIBG": "Big Bang",
            "SPNA": "Supernova",
            "TS": "Terrible Shadow",

            "IKRM": "Inakuni Raimon",
            "BT": "Bastion",
            "AS": "Anima Sana",
            "PS": "École Polaris",
            "AA": "École Alia",
            "LD": "Lambda",
            "SN": "Sélène",

            "RB": "Red Bison",
            "SHST": "Shining Satans",
            "ET": "Eternal Dancers",
            "PHoA": "Phoenix Army of Arab",
            "SAoA": "Soccer Acrobatic of Arab",
            "IG": "Invincible Giant",
            "SU": "Star Unicorn",
            "NI": "Navy Invaders",
            "PFS": "Perfect Spark",
            "OdS": "Olé de Samba",
            "GQ": "Guardians of Queen",
            "SO": "Shadow of Orion"
            }

        self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs","Inazuma Eleven 1"))
        self.FolderPath2 = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Formation"))
        self.FolderPath3 = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Coach", "Inazuma Eleven 1"))

        self.Joueurs = [os.path.join(self.FolderPath, fichier) for fichier in os.listdir(self.FolderPath) if os.path.isfile(os.path.join(self.FolderPath, fichier)) and fichier.lower().endswith(".png")]
        self.Formation = [os.path.join(self.FolderPath2, fichier) for fichier in os.listdir(self.FolderPath2) if os.path.isfile(os.path.join(self.FolderPath2, fichier)) and fichier.lower().endswith(".png")]
        self.Coach  = [os.path.join(self.FolderPath3, fichier) for fichier in os.listdir(self.FolderPath3) if os.path.isfile(os.path.join(self.FolderPath3, fichier)) and fichier.lower().endswith(".png")]
        print(self.Joueurs)
        self.FW = []
        self.GK = []
        self.MF = []
        self.DF = []

        self.CurrentList = self.Formation

        # Parcourir la liste des joueurs et les classer
        for joueur in self.Joueurs:
            # Extraire le nom de fichier
            nom_fichier = os.path.basename(joueur)

            # Vérifier la présence de chaque chaîne de caractères et classer le joueur en conséquence
            if "(FW)" in nom_fichier:
                self.FW.append(joueur)
            elif "(GK)" in nom_fichier:
                self.GK.append(joueur)
            elif "(MF)" in nom_fichier:
                self.MF.append(joueur)
            elif "(DF)" in nom_fichier:
                self.DF.append(joueur)
                
        ####################################################################
        ####################################################################
                
        MainWindow.setObjectName("Random Draft Inazuma Eleven")
        MainWindow.resize(668, 931)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 967))
        

        MainWindow.setStyleSheet(u"background-image:url(:/image/background2.png)\n"
"")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setStyleSheet("Line {\n"
"color: #FFF;\n"
"}")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setBold(False)
        self.label_Title.setFont(font)
        self.label_Title.setStyleSheet("\n"
"QLabel{\n"
"color : #FFF\n"
"}\n"
"")
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout.addWidget(self.label_Title, 0, QtCore.Qt.AlignHCenter)
        self.comboBox_Saison = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_Saison.setFont(font)
        self.comboBox_Saison.setStyleSheet("    QComboBox {\n"
"min-width: 180px;;\n"
"min-height: 30px;\n"
"border-radius: 7px;\n"
"color: #FFF;\n"
"background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QListView::item {\n"
"color: #FFF;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: rgb(34, 36, 44);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.comboBox_Saison.setEditable(False)
        self.comboBox_Saison.setCurrentText("Inazuma Eleven 1")
        self.comboBox_Saison.setPlaceholderText("")
        self.comboBox_Saison.setObjectName("comboBox_Saison")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.verticalLayout.addWidget(self.comboBox_Saison)
        self.comboBox_type = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_type.setFont(font)
        self.comboBox_type.setStyleSheet("QComboBox {\n"
"min-width: 180px;;\n"
"min-height: 30px;\n"
"\n"
"border-radius: 7px;\n"
"color: #FFF;\n"
"background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QListView {\n"
"background-color: rgb(34, 36, 44);\n"
"}\n"
"QListView::item {\n"
"color: #FFF;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: rgb(34, 36, 44);\n"
"}")
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.verticalLayout.addWidget(self.comboBox_type)
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(250, 56))
        self.pushButton_Start.setMaximumSize(QtCore.QSize(256, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"color: #FFF;\n"
"\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"max-width: 250px;;\n"
"min-height: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}\n"
"")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.verticalLayout.addWidget(self.pushButton_Start, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("Line {\n"
"color: #FFF;\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_Row = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Row.setObjectName("horizontalLayout_Row")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row.addItem(spacerItem1)
        self.verticalLayout_Character1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character1.setObjectName("verticalLayout_Character1")
        self.label_team1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        self.label_team1.setFont(font)
        self.label_team1.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team1.setObjectName("label_team1")
        self.verticalLayout_Character1.addWidget(self.label_team1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image1.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image1.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image1.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image1.setLineWidth(2)
        self.label_Image1.setText("")
        self.label_Image1.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image1.setScaledContents(True)
        self.label_Image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image1.setObjectName("label_Image1")
        self.verticalLayout_Character1.addWidget(self.label_Image1, 0, QtCore.Qt.AlignHCenter)
        self.label_Name1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name1.setFont(font)
        self.label_Name1.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name1.setObjectName("label_Name1")
        self.verticalLayout_Character1.addWidget(self.label_Name1)
        self.pushButton_Select1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select1.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_Select1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(12)
        self.pushButton_Select1.setFont(font)
        self.pushButton_Select1.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select1.setObjectName("pushButton_Select1")
        self.verticalLayout_Character1.addWidget(self.pushButton_Select1, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row.addLayout(self.verticalLayout_Character1)
        self.verticalLayout_Character2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character2.setObjectName("verticalLayout_Character2")
        self.label_team2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        self.label_team2.setFont(font)
        self.label_team2.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team2.setObjectName("label_team2")
        self.verticalLayout_Character2.addWidget(self.label_team2, 0, QtCore.Qt.AlignHCenter)
        self.label_Image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image2.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image2.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image2.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image2.setLineWidth(2)
        self.label_Image2.setText("")
        self.label_Image2.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image2.setScaledContents(True)
        self.label_Image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image2.setWordWrap(False)
        self.label_Image2.setObjectName("label_Image2")
        self.verticalLayout_Character2.addWidget(self.label_Image2, 0, QtCore.Qt.AlignHCenter)
        self.label_Name2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name2.setFont(font)
        self.label_Name2.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name2.setObjectName("label_Name2")
        self.verticalLayout_Character2.addWidget(self.label_Name2)
        self.pushButton_Select2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select2.setFont(font)
        self.pushButton_Select2.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select2.setObjectName("pushButton_Select2")
        self.verticalLayout_Character2.addWidget(self.pushButton_Select2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row.addLayout(self.verticalLayout_Character2)
        self.verticalLayout_Character3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character3.setObjectName("verticalLayout_Character3")
        self.label_team3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        self.label_team3.setFont(font)
        self.label_team3.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team3.setObjectName("label_team3")
        self.verticalLayout_Character3.addWidget(self.label_team3, 0, QtCore.Qt.AlignHCenter)
        self.label_Image3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image3.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image3.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image3.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image3.setLineWidth(2)
        self.label_Image3.setText("")
        self.label_Image3.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image3.setScaledContents(True)
        self.label_Image3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image3.setObjectName("label_Image3")
        self.verticalLayout_Character3.addWidget(self.label_Image3, 0, QtCore.Qt.AlignHCenter)
        self.label_Name3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name3.setFont(font)
        self.label_Name3.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name3.setObjectName("label_Name3")
        self.verticalLayout_Character3.addWidget(self.label_Name3)
        self.pushButton_Select3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select3.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select3.setFont(font)
        self.pushButton_Select3.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select3.setObjectName("pushButton_Select3")
        self.verticalLayout_Character3.addWidget(self.pushButton_Select3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row.addLayout(self.verticalLayout_Character3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_Row)
        self.horizontalLayout_Row2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Row2.setObjectName("horizontalLayout_Row2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row2.addItem(spacerItem3)
        self.verticalLayout_Character4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character4.setObjectName("verticalLayout_Character4")
        self.label_team4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        self.label_team4.setFont(font)
        self.label_team4.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team4.setObjectName("label_team4")
        self.verticalLayout_Character4.addWidget(self.label_team4, 0, QtCore.Qt.AlignHCenter)
        self.label_Image4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image4.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image4.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image4.setAutoFillBackground(False)
        self.label_Image4.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image4.setLineWidth(2)
        self.label_Image4.setText("")
        self.label_Image4.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image4.setScaledContents(True)
        self.label_Image4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image4.setObjectName("label_Image4")
        self.verticalLayout_Character4.addWidget(self.label_Image4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Name4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name4.setFont(font)
        self.label_Name4.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name4.setObjectName("label_Name4")
        self.verticalLayout_Character4.addWidget(self.label_Name4)
        self.pushButton_Select4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select4.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select4.setFont(font)
        self.pushButton_Select4.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select4.setObjectName("pushButton_Select4")
        self.verticalLayout_Character4.addWidget(self.pushButton_Select4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row2.addLayout(self.verticalLayout_Character4)
        self.verticalLayout_Character5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character5.setObjectName("verticalLayout_Character5")
        self.label_team5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        self.label_team5.setFont(font)
        self.label_team5.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team5.setObjectName("label_team5")
        self.verticalLayout_Character5.addWidget(self.label_team5, 0, QtCore.Qt.AlignHCenter)
        self.label_Image5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image5.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image5.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image5.setAutoFillBackground(False)
        self.label_Image5.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image5.setLineWidth(2)
        self.label_Image5.setText("")
        self.label_Image5.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image5.setScaledContents(True)
        self.label_Image5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image5.setObjectName("label_Image5")
        self.verticalLayout_Character5.addWidget(self.label_Image5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Name5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name5.setFont(font)
        self.label_Name5.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name5.setObjectName("label_Name5")
        self.verticalLayout_Character5.addWidget(self.label_Name5)
        self.pushButton_Select5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select5.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select5.setFont(font)
        self.pushButton_Select5.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select5.setObjectName("pushButton_Select5")
        self.verticalLayout_Character5.addWidget(self.pushButton_Select5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row2.addLayout(self.verticalLayout_Character5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_Row2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("Line {\n"
"color: #FFF;\n"
"}")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_YourTeam = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setBold(False)
        self.label_YourTeam.setFont(font)
        self.label_YourTeam.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_YourTeam.setObjectName("label_YourTeam")
        self.verticalLayout.addWidget(self.label_YourTeam, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.SelectedFormation = QtWidgets.QLabel(self.centralwidget)
        self.SelectedFormation.setMaximumSize(QtCore.QSize(90, 90))
        self.SelectedFormation.setText("")
        self.SelectedFormation.setPixmap(QtGui.QPixmap("Resource/field.svg"))
        self.SelectedFormation.setScaledContents(True)
        self.SelectedFormation.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedFormation.setObjectName("SelectedFormation")
        self.horizontalLayout_3.addWidget(self.SelectedFormation, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SelectedCharacter01 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter01.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter01.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter01.setText("")
        self.SelectedCharacter01.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter01.setScaledContents(False)
        self.SelectedCharacter01.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter01.setObjectName("SelectedCharacter01")
        self.gridLayout.addWidget(self.SelectedCharacter01, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter04 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter04.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter04.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter04.setText("")
        self.SelectedCharacter04.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter04.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter04.setObjectName("SelectedCharacter04")
        self.gridLayout.addWidget(self.SelectedCharacter04, 1, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter09 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter09.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter09.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter09.setText("")
        self.SelectedCharacter09.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter09.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter09.setObjectName("SelectedCharacter09")
        self.gridLayout.addWidget(self.SelectedCharacter09, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter11 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter11.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter11.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter11.setText("")
        self.SelectedCharacter11.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter11.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter11.setObjectName("SelectedCharacter11")
        self.gridLayout.addWidget(self.SelectedCharacter11, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter13 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter13.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter13.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter13.setText("")
        self.SelectedCharacter13.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter13.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter13.setObjectName("SelectedCharacter13")
        self.gridLayout.addWidget(self.SelectedCharacter13, 2, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter07 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter07.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter07.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SelectedCharacter07.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter07.setText("")
        self.SelectedCharacter07.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter07.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter07.setObjectName("SelectedCharacter07")
        self.gridLayout.addWidget(self.SelectedCharacter07, 1, 8, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter16 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter16.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter16.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter16.setText("")
        self.SelectedCharacter16.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter16.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter16.setObjectName("SelectedCharacter16")
        self.gridLayout.addWidget(self.SelectedCharacter16, 2, 9, 1, 1, QtCore.Qt.AlignVCenter)
        self.SelectedCharacter06 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter06.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter06.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter06.setText("")
        self.SelectedCharacter06.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter06.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter06.setObjectName("SelectedCharacter06")
        self.gridLayout.addWidget(self.SelectedCharacter06, 1, 7, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter14 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter14.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter14.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter14.setText("")
        self.SelectedCharacter14.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter14.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter14.setObjectName("SelectedCharacter14")
        self.gridLayout.addWidget(self.SelectedCharacter14, 2, 7, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter15 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter15.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SelectedCharacter15.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter15.setText("")
        self.SelectedCharacter15.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter15.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter15.setObjectName("SelectedCharacter15")
        self.gridLayout.addWidget(self.SelectedCharacter15, 2, 8, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter03 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter03.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter03.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter03.setText("")
        self.SelectedCharacter03.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter03.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter03.setObjectName("SelectedCharacter03")
        self.gridLayout.addWidget(self.SelectedCharacter03, 1, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter08 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter08.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter08.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter08.setText("")
        self.SelectedCharacter08.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter08.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter08.setObjectName("SelectedCharacter08")
        self.gridLayout.addWidget(self.SelectedCharacter08, 1, 9, 1, 1, QtCore.Qt.AlignHCenter)
        self.SelectedCharacter12 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter12.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter12.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter12.setText("")
        self.SelectedCharacter12.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter12.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter12.setObjectName("SelectedCharacter12")
        self.gridLayout.addWidget(self.SelectedCharacter12, 2, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter05 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter05.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter05.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter05.setText("")
        self.SelectedCharacter05.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter05.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter05.setObjectName("SelectedCharacter05")
        self.gridLayout.addWidget(self.SelectedCharacter05, 1, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter10 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter10.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter10.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter10.setText("")
        self.SelectedCharacter10.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter10.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter10.setObjectName("SelectedCharacter10")
        self.gridLayout.addWidget(self.SelectedCharacter10, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter02 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter02.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter02.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter02.setText("")
        self.SelectedCharacter02.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCharacter02.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter02.setObjectName("SelectedCharacter02")
        self.gridLayout.addWidget(self.SelectedCharacter02, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.SelectedCoach = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCoach.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCoach.setText("")
        self.SelectedCoach.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.SelectedCoach.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCoach.setObjectName("SelectedCoach")
        self.horizontalLayout_3.addWidget(self.SelectedCoach, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setStyleSheet("Line {\n"
"color: #FFF;\n"
"}")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        MainWindow.setCentralWidget(self.centralwidget)

        ###################################################################################
        ###################################################################################
        ###################################################################################
        self.label_Image4.hide()
        self.label_Name4.hide()
        self.label_team4.hide()
        self.label_Image5.hide()
        self.label_Name5.hide()
        self.label_team5.hide()
        self.pushButton_Select4.hide()
        self.pushButton_Select5.hide()
        
        self.pushButton_Start.clicked.connect(self.StartRandomisation) 
        self.comboBox_type.currentIndexChanged.connect(self.on_comboBox_type_changed)
        self.comboBox_Saison.currentIndexChanged.connect(self.on_comboBox_Saison_changed)

        self.pushButton_Select1.clicked.connect(self.pushButton_Select1_clicked)
        self.pushButton_Select2.clicked.connect(self.pushButton_Select2_clicked)
        self.pushButton_Select3.clicked.connect(self.pushButton_Select3_clicked)
        self.pushButton_Select4.clicked.connect(self.pushButton_Select4_clicked)
        self.pushButton_Select5.clicked.connect(self.pushButton_Select5_clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random Draft Inazuma Eleven"))
        self.label_Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">Random Draft Inazuma Eleven</span></p></body></html>"))
        self.comboBox_Saison.setItemText(0, _translate("MainWindow", "Inazuma Eleven 1"))
        self.comboBox_Saison.setItemText(1, _translate("MainWindow", "Inazuma Eleven 2"))
        self.comboBox_Saison.setItemText(2, _translate("MainWindow", "Inazuma Eleven 3"))
        self.comboBox_Saison.setItemText(3, _translate("MainWindow", "Inazuma Eleven GO"))
        self.comboBox_Saison.setItemText(4, _translate("MainWindow", "Inazuma Eleven GO Chrono Stones"))
        self.comboBox_Saison.setItemText(5, _translate("MainWindow", "Inazuma Eleven GO Galaxy"))
        self.comboBox_Saison.setItemText(6, _translate("MainWindow", "Inazuma Eleven Ares"))
        self.comboBox_Saison.setItemText(7, _translate("MainWindow", "Inazuma Eleven Orion"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Formation"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Gardien"))
        self.comboBox_type.setItemText(2, _translate("MainWindow", "Défenseur"))
        self.comboBox_type.setItemText(3, _translate("MainWindow", "Milieu"))
        self.comboBox_type.setItemText(4, _translate("MainWindow", "Attaquant"))
        self.comboBox_type.setItemText(5, _translate("MainWindow", "Coach"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start Random pick"))
        self.label_team1.setText(_translate("MainWindow", "Team 1"))
        self.label_Name1.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select1.setText(_translate("MainWindow", "Select"))
        self.label_team2.setText(_translate("MainWindow", "Team 2"))
        self.label_Name2.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select2.setText(_translate("MainWindow", "Select"))
        self.label_team3.setText(_translate("MainWindow", "Team 3"))
        self.label_Name3.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select3.setText(_translate("MainWindow", "Select"))
        self.label_team4.setText(_translate("MainWindow", "Team 4"))
        self.label_Name4.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select4.setText(_translate("MainWindow", "Select"))
        self.label_team5.setText(_translate("MainWindow", "Team 5"))
        self.label_Name5.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select5.setText(_translate("MainWindow", "Select"))
        self.label_YourTeam.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Your Team</span></p></body></html>"))


    def on_comboBox_Saison_changed(self, index):
        # Fonction appelée lorsque la sélection de la combo box change
        selected_option = self.comboBox_Saison.currentText()
        
        if selected_option == "Inazuma Eleven 1":
            self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs","Inazuma Eleven 1"))
        if selected_option == "Inazuma Eleven 2":
            self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven 2"))
        if selected_option == "Inazuma Eleven 3":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven 3"))
        if selected_option == "Inazuma Eleven GO":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven GO"))
        if selected_option == "Inazuma Eleven GO Chrono Stones":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven GO Chrono Stones"))
        if selected_option == "Inazuma Eleven GO Galaxy":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven GO Galaxy"))
        if selected_option == "Inazuma Eleven Ares":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven Ares"))
        if selected_option == "Inazuma Eleven Orion":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Joueurs", "Inazuma Eleven Orion"))



        self.Joueurs = [os.path.join(self.FolderPath, fichier) for fichier in os.listdir(self.FolderPath) if os.path.isfile(os.path.join(self.FolderPath, fichier)) and fichier.lower().endswith(".png")]
        # Initialiser les listes
        self.FW = []
        self.GK = []
        self.MF = []
        self.DF = []
        self.on_comboBox_type_changed(index = 0)

        # Parcourir la liste des joueurs et les classer
        for joueur in self.Joueurs:
            # Extraire le nom de fichier
            nom_fichier = os.path.basename(joueur)

            # Vérifier la présence de chaque chaîne de caractères et classer le joueur en conséquence
            if "(FW)" in nom_fichier:
                self.FW.append(joueur)
            elif "(GK)" in nom_fichier:
                self.GK.append(joueur)
            elif "(MF)" in nom_fichier:
                self.MF.append(joueur)
            elif "(DF)" in nom_fichier:
                self.DF.append(joueur)

    def on_comboBox_type_changed(self, index):
        _translate = QtCore.QCoreApplication.translate
        # Fonction appelée lorsque la sélection de la combo box change
        selected_option = self.comboBox_type.currentText()
        self.Status = False

        FolderPathCoach = os.path.abspath(os.path.join(os.getcwd(), "Resource", "Coach", self.comboBox_Saison.currentText()))
        
        if self.selected_previous_option == "Coach" or self.selected_previous_option == "Formation":
            self.label_Image4.show()
            self.label_Name4.show()
            self.label_team4.show()
            self.label_Image5.show()
            self.label_Name5.show()
            self.label_team5.show()
            self.pushButton_Select4.show()
            self.pushButton_Select5.show()
            self.label_Image4.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
            self.label_Image5.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))        
            self.label_team4.setText(_translate("MainWindow", "Team 4"))
            self.label_Name4.setText(_translate("MainWindow", "Prénom Nom - Genre"))
            self.label_team5.setText(_translate("MainWindow", "Team 5"))
            self.label_Name5.setText(_translate("MainWindow", "Prénom Nom - Genre"))
            self.pushButton_Select4.setEnabled(False)
            self.pushButton_Select5.setEnabled(False)

        if selected_option == "Formation":
            self.CurrentList = self.Formation
            self.label_Image4.hide()
            self.label_Name4.hide()
            self.label_team4.hide()
            self.label_Image5.hide()
            self.label_Name5.hide()
            self.label_team5.hide()
            self.pushButton_Select4.hide()
            self.pushButton_Select5.hide()
            self.Status = True
        if selected_option == "Coach":
            self.CurrentList = [os.path.join(FolderPathCoach, fichier) for fichier in os.listdir(FolderPathCoach) if os.path.isfile(os.path.join(FolderPathCoach, fichier)) and fichier.lower().endswith(".png")]
            self.label_Image4.hide()
            self.label_Name4.hide()
            self.label_team4.hide()
            self.label_Image5.hide()
            self.label_Name5.hide()
            self.label_team5.hide()
            self.pushButton_Select4.hide()
            self.pushButton_Select5.hide()
            self.Status = True       
        if selected_option == "Gardien":
            self.CurrentList = self.GK
            self.Status = True
        if selected_option == "Défenseur":
            self.CurrentList = self.DF
            self.Status = True
        if selected_option == "Milieu":
            self.CurrentList = self.MF
            self.Status = True
        if selected_option == "Attaquant":
            self.CurrentList = self.FW
            self.Status = True

        self.selected_previous_option = selected_option

    def selectedCharacter(self,pathPerso):
        if self.comboBox_type.currentText() == "Formation":
            self.SelectedFormation.setPixmap(QtGui.QPixmap(pathPerso))
            return
        
        if self.comboBox_type.currentText() == "Coach":
            self.SelectedCoach.setPixmap(QtGui.QPixmap(pathPerso))
            return
        
        if self.Status == True:
            self.counter += 1

            if self.counter == 1:
                self.SelectedCharacter01.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 2:
                self.SelectedCharacter02.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 3:
                self.SelectedCharacter03.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 4:
                self.SelectedCharacter04.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 5:
                self.SelectedCharacter05.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 6:
                self.SelectedCharacter06.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 7:
                self.SelectedCharacter07.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 8:
                self.SelectedCharacter08.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 9:
                self.SelectedCharacter09.setPixmap(QtGui.QPixmap(pathPerso))
            
            if self.counter == 10:
                self.SelectedCharacter10.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 11:
                self.SelectedCharacter11.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 12:
                self.SelectedCharacter12.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 13:
                self.SelectedCharacter13.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 14:
                self.SelectedCharacter14.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 15:
                self.SelectedCharacter15.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 16:
                self.SelectedCharacter16.setPixmap(QtGui.QPixmap(pathPerso))

        return

    def pushButton_Select1_clicked(self):
        self.selectedCharacter(self.CurrentList[-5])
        self.yourTeam.append(self.CurrentList[-5])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-5+self.offset] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-5])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-5])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-5])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-5])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-5])
        
        self.label_Image2.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))

    def pushButton_Select2_clicked(self):
        self.selectedCharacter(self.CurrentList[-4])
        self.yourTeam.append(self.CurrentList[-4])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-4] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-4])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-4])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-4])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-4])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-4])

        self.label_Image1.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))

    def pushButton_Select3_clicked(self):
        self.selectedCharacter(self.CurrentList[-3])
        self.yourTeam.append(self.CurrentList[-3])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-3] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-3])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-3])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-3])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-3])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-3])

        self.label_Image1.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image2.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))

    def pushButton_Select4_clicked(self):
        self.selectedCharacter(self.CurrentList[-2])
        self.yourTeam.append(self.CurrentList[-2])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-2] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-2])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-2])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-2])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-2])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-2])

        self.label_Image1.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image2.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))

    def pushButton_Select5_clicked(self):
        self.selectedCharacter(self.CurrentList[-1])
        self.yourTeam.append(self.CurrentList[-1])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-1] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-1])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-1])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-1])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-1])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-1])

        self.label_Image1.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image2.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("Resource/character-placeholder.png"))


    def StartRandomisation(self):
        self.offset = 0
        self.pushButton_Start.setEnabled(False)
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        _translate = QtCore.QCoreApplication.translate

        # Parcourez la liste des joueurs et mettez à jour les images des labels
        
        self.TotalItems = self.Nb_Cycle * len(self.CurrentList)  # Total des éléments à travers toutes les boucles

        for j in range(self.Nb_Cycle):
            random.shuffle(self.CurrentList)
            for i, self.BaseNom in enumerate(self.CurrentList):
                #print(self.BaseNom)

                # Choisissez le label en fonction de l'index
                if i % 5 == 0:
                    label = self.label_Image1
                    label2 = self.label_Name1
                    label3 = self.label_team1
                elif i % 5 == 1:
                    label = self.label_Image2
                    label2 = self.label_Name2
                    label3 = self.label_team2
                elif i % 5 == 2:
                    label = self.label_Image3
                    label2 = self.label_Name3
                    label3 = self.label_team3
                elif i % 5 == 3:
                    label = self.label_Image4
                    label2 = self.label_Name4
                    label3 = self.label_team4
                else:
                    label = self.label_Image5
                    label2 = self.label_Name5
                    label3 = self.label_team5

                nom_fichier = os.path.basename(self.BaseNom)

                # Définir une expression régulière pour extraire le prénom, le nom et le genre
                if self.comboBox_type.currentText()== "Formation":
                    # Expression régulière
                    pattern = re.compile(r'\((.*?)\) (.+?)\.png')
                    nom_fichier1 = os.path.basename(self.CurrentList[-5])
                    match1 = pattern.match(nom_fichier1)
                    # Effectuer la correspondance avec le nom du fichier
                    match = pattern.match(nom_fichier)
                    # Extraire le prénom, le nom et le genre à partir des groupes capturants
                    team = match.group(1)
                    prenom_nom = match.group(2)
                    # Mettez à jour l'image du label
                    label2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                    label.setPixmap(QtGui.QPixmap(self.BaseNom))
                    label3.setText(_translate("MainWindow", "{}".format(team)))
                elif self.comboBox_type.currentText() == "Coach":
                    # Expression régulière
                    pattern = re.compile(r'\((.*?)\) (.+?)\.png')            
                    # Effectuer la correspondance avec le nom du fichier
                    match = pattern.match(nom_fichier)
                    # Extraire le prénom, le nom et le genre à partir des groupes capturants
                    team = match.group(1)
                    prenom_nom = match.group(2)
                    # Mettez à jour l'image du label
                    label2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                    label.setPixmap(QtGui.QPixmap(self.BaseNom))
                    label3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))
                else:
                    pattern = re.compile(r'\((.*?)\) \((.*?)\) \((.*?)\) (.+?)\.png')
                    match = pattern.match(nom_fichier)
                    # Extraire le prénom, le nom et le genre à partir des groupes capturants
                    team = match.group(1)
                    genre = match.group(3)
                    prenom_nom = match.group(4)
                    # Mettez à jour l'image du label
                    label2.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                    label.setPixmap(QtGui.QPixmap(self.BaseNom))
                    label3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

                progress_percentage = (i + len(self.CurrentList) * j) / self.TotalItems

                if progress_percentage < 0.6:
                    delay_factor = 0.1  # Vitesse rapide pour les 70% premiers
                elif progress_percentage < 0.7:
                    delay_factor = 0.3  # Ralentissement progressif pour les 20% suivants
                else:
                    delay_factor = 1000000  # Très lent pour les 10% derniers
                delay = 1/(1 + (self.TotalItems - i - len(self.CurrentList) * j) / delay_factor)

                # Convertir le délai de secondes à millisecondes
                delay_ms = delay /1000

                # Actualisez l'affichage à chaque itération
                #print(f"Iteration {1 + (self.TotalItems - i - len(self.CurrentList) * j)}/{(len(self.CurrentList)*self.Nb_Cycle)}, Delay: {delay_ms} ms\t",delay_factor)
                time.sleep(delay_ms)
                QtWidgets.QApplication.processEvents()
        

        if self.comboBox_type.currentText()== "Formation":
            nom_fichier1 = os.path.basename(self.CurrentList[-5])
            match1 = pattern.match(nom_fichier1)
            if match1:
                team = match1.group(1)
                prenom_nom = match1.group(2)
                self.label_Name1.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team1.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier2 = os.path.basename(self.CurrentList[-4])
            match2 = pattern.match(nom_fichier2)
            if match2:
                team = match2.group(1)
                prenom_nom = match2.group(2)
                self.label_Name2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team2.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier3 = os.path.basename(self.CurrentList[-3])
            match3 = pattern.match(nom_fichier3)
            if match3:
                team = match3.group(1)
                prenom_nom = match3.group(2)
                self.label_Name3.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team3.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier4 = os.path.basename(self.CurrentList[-2])
            match4 = pattern.match(nom_fichier4)
            if match4:
                team = match4.group(1)
                prenom_nom = match4.group(2)
                self.label_Name4.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team4.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier5 = os.path.basename(self.CurrentList[-1])
            match5 = pattern.match(nom_fichier5)
            if match5:
                team = match5.group(1)
                prenom_nom = match5.group(2)
                self.label_Name5.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team5.setText(_translate("MainWindow", "{}".format(team)))

        elif self.comboBox_type.currentText() == "Coach":
            nom_fichier1 = os.path.basename(self.CurrentList[-5])
            match1 = pattern.match(nom_fichier1)
            if match1:
                team = match1.group(1)
                prenom_nom = match1.group(2)
                self.label_Name1.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team1.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier2 = os.path.basename(self.CurrentList[-4])
            match2 = pattern.match(nom_fichier2)
            if match2:
                team = match2.group(1)
                prenom_nom = match2.group(2)
                self.label_Name2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team2.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier3 = os.path.basename(self.CurrentList[-3])
            match3 = pattern.match(nom_fichier3)
            if match3:
                team = match3.group(1)
                prenom_nom = match3.group(2)
                self.label_Name3.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier4 = os.path.basename(self.CurrentList[-2])
            match4 = pattern.match(nom_fichier4)
            if match4:
                team = match4.group(1)
                prenom_nom = match4.group(2)
                self.label_Name4.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team4.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier5 = os.path.basename(self.CurrentList[-1])
            match5 = pattern.match(nom_fichier5)
            if match5:
                team = match5.group(1)
                prenom_nom = match5.group(2)
                self.label_Name5.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team5.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))
        else:
            nom_fichier1 = os.path.basename(self.CurrentList[-5])
            match1 = pattern.match(nom_fichier1)
            if match1:
                team = match1.group(1)
                genre = match1.group(3)
                prenom_nom = match1.group(4)
                self.label_Name1.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team1.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier2 = os.path.basename(self.CurrentList[-4])
            match2 = pattern.match(nom_fichier2)
            if match2:
                team = match2.group(1)
                genre = match2.group(3)
                prenom_nom = match2.group(4)
                self.label_Name2.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team2.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier3 = os.path.basename(self.CurrentList[-3])
            match3 = pattern.match(nom_fichier3)
            if match3:
                team = match3.group(1)
                genre = match3.group(3)
                prenom_nom = match3.group(4)
                self.label_Name3.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier4 = os.path.basename(self.CurrentList[-2])
            match4 = pattern.match(nom_fichier4)
            if match4:
                team = match4.group(1)
                genre = match4.group(3)
                prenom_nom = match4.group(4)
                self.label_Name4.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team4.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier5 = os.path.basename(self.CurrentList[-1])
            match5 = pattern.match(nom_fichier5)
            if match5:
                team = match5.group(1)
                genre = match5.group(3)
                prenom_nom = match5.group(4)
                self.label_Name5.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team5.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))


        self.label_Image1.setPixmap(QtGui.QPixmap(self.CurrentList[-5]))
        self.label_Image2.setPixmap(QtGui.QPixmap(self.CurrentList[-4]))
        self.label_Image3.setPixmap(QtGui.QPixmap(self.CurrentList[-3]))
        self.label_Image4.setPixmap(QtGui.QPixmap(self.CurrentList[-2]))
        self.label_Image5.setPixmap(QtGui.QPixmap(self.CurrentList[-1]))
                
        self.pushButton_Start.setEnabled(True)
        self.pushButton_Select1.setEnabled(True)
        self.pushButton_Select2.setEnabled(True)
        self.pushButton_Select3.setEnabled(True)
        self.pushButton_Select4.setEnabled(True)
        self.pushButton_Select5.setEnabled(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
