# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inazumaCSS_cloud.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 931)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 967))
        MainWindow.setStyleSheet("background-image:url(:/image/background2.png)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setStyleSheet("Line {\n"
"color: #FFF;\n"
"}")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setBold(False)
        self.label_Title.setFont(font)
        self.label_Title.setStyleSheet("\n"
"QLabel{\n"
"color : #FFF\n"
"}\n"
"")
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout.addWidget(self.label_Title, 0, QtCore.Qt.AlignHCenter)
        self.comboBox_Saison = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_Saison.setFont(font)
        self.comboBox_Saison.setStyleSheet("    QComboBox {\n"
"min-width: 180px;;\n"
"min-height: 30px;\n"
"border-radius: 7px;\n"
"color: #FFF;\n"
"background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QListView::item {\n"
"color: #FFF;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: rgb(34, 36, 44);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.comboBox_Saison.setEditable(False)
        self.comboBox_Saison.setCurrentText("Inazuma Eleven 1")
        self.comboBox_Saison.setPlaceholderText("")
        self.comboBox_Saison.setObjectName("comboBox_Saison")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.comboBox_Saison.addItem("")
        self.verticalLayout.addWidget(self.comboBox_Saison)
        self.comboBox_type = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(10)
        font.setBold(False)
        self.comboBox_type.setFont(font)
        self.comboBox_type.setStyleSheet("QComboBox {\n"
"min-width: 180px;;\n"
"min-height: 30px;\n"
"\n"
"border-radius: 7px;\n"
"color: #FFF;\n"
"background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QListView {\n"
"background-color: rgb(34, 36, 44);\n"
"}\n"
"QListView::item {\n"
"color: #FFF;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"background-color: rgb(70, 80,87);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: rgb(34, 36, 44);\n"
"}")
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.verticalLayout.addWidget(self.comboBox_type)
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(250, 56))
        self.pushButton_Start.setMaximumSize(QtCore.QSize(256, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"color: #FFF;\n"
"\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"max-width: 250px;;\n"
"min-height: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}\n"
"")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.verticalLayout.addWidget(self.pushButton_Start, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("Line {\n"
"color: #FFF;\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_Row = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Row.setObjectName("horizontalLayout_Row")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row.addItem(spacerItem1)
        self.verticalLayout_Character1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character1.setObjectName("verticalLayout_Character1")
        self.label_team1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        self.label_team1.setFont(font)
        self.label_team1.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team1.setObjectName("label_team1")
        self.verticalLayout_Character1.addWidget(self.label_team1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image1.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image1.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image1.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image1.setLineWidth(2)
        self.label_Image1.setText("")
        self.label_Image1.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.label_Image1.setScaledContents(True)
        self.label_Image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image1.setObjectName("label_Image1")
        self.verticalLayout_Character1.addWidget(self.label_Image1, 0, QtCore.Qt.AlignHCenter)
        self.label_Name1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name1.setFont(font)
        self.label_Name1.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name1.setObjectName("label_Name1")
        self.verticalLayout_Character1.addWidget(self.label_Name1)
        self.pushButton_Select1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select1.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_Select1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(12)
        self.pushButton_Select1.setFont(font)
        self.pushButton_Select1.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select1.setObjectName("pushButton_Select1")
        self.verticalLayout_Character1.addWidget(self.pushButton_Select1, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row.addLayout(self.verticalLayout_Character1)
        self.verticalLayout_Character2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character2.setObjectName("verticalLayout_Character2")
        self.label_team2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        self.label_team2.setFont(font)
        self.label_team2.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team2.setObjectName("label_team2")
        self.verticalLayout_Character2.addWidget(self.label_team2, 0, QtCore.Qt.AlignHCenter)
        self.label_Image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image2.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image2.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image2.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image2.setLineWidth(2)
        self.label_Image2.setText("")
        self.label_Image2.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.label_Image2.setScaledContents(True)
        self.label_Image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image2.setWordWrap(False)
        self.label_Image2.setObjectName("label_Image2")
        self.verticalLayout_Character2.addWidget(self.label_Image2, 0, QtCore.Qt.AlignHCenter)
        self.label_Name2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name2.setFont(font)
        self.label_Name2.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name2.setObjectName("label_Name2")
        self.verticalLayout_Character2.addWidget(self.label_Name2)
        self.pushButton_Select2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select2.setFont(font)
        self.pushButton_Select2.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select2.setObjectName("pushButton_Select2")
        self.verticalLayout_Character2.addWidget(self.pushButton_Select2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row.addLayout(self.verticalLayout_Character2)
        self.verticalLayout_Character3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character3.setObjectName("verticalLayout_Character3")
        self.label_team3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        font.setBold(False)
        self.label_team3.setFont(font)
        self.label_team3.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team3.setObjectName("label_team3")
        self.verticalLayout_Character3.addWidget(self.label_team3, 0, QtCore.Qt.AlignHCenter)
        self.label_Image3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image3.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image3.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image3.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image3.setLineWidth(2)
        self.label_Image3.setText("")
        self.label_Image3.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.label_Image3.setScaledContents(True)
        self.label_Image3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image3.setObjectName("label_Image3")
        self.verticalLayout_Character3.addWidget(self.label_Image3, 0, QtCore.Qt.AlignHCenter)
        self.label_Name3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name3.setFont(font)
        self.label_Name3.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name3.setObjectName("label_Name3")
        self.verticalLayout_Character3.addWidget(self.label_Name3)
        self.pushButton_Select3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select3.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select3.setFont(font)
        self.pushButton_Select3.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select3.setObjectName("pushButton_Select3")
        self.verticalLayout_Character3.addWidget(self.pushButton_Select3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row.addLayout(self.verticalLayout_Character3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_Row)
        self.horizontalLayout_Row2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Row2.setObjectName("horizontalLayout_Row2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row2.addItem(spacerItem3)
        self.verticalLayout_Character4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character4.setObjectName("verticalLayout_Character4")
        self.label_team4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        self.label_team4.setFont(font)
        self.label_team4.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team4.setObjectName("label_team4")
        self.verticalLayout_Character4.addWidget(self.label_team4, 0, QtCore.Qt.AlignHCenter)
        self.label_Image4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image4.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image4.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image4.setAutoFillBackground(False)
        self.label_Image4.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image4.setLineWidth(2)
        self.label_Image4.setText("")
        self.label_Image4.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.label_Image4.setScaledContents(True)
        self.label_Image4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image4.setObjectName("label_Image4")
        self.verticalLayout_Character4.addWidget(self.label_Image4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Name4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name4.setFont(font)
        self.label_Name4.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name4.setObjectName("label_Name4")
        self.verticalLayout_Character4.addWidget(self.label_Name4)
        self.pushButton_Select4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select4.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select4.setFont(font)
        self.pushButton_Select4.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select4.setObjectName("pushButton_Select4")
        self.verticalLayout_Character4.addWidget(self.pushButton_Select4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row2.addLayout(self.verticalLayout_Character4)
        self.verticalLayout_Character5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Character5.setObjectName("verticalLayout_Character5")
        self.label_team5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(11)
        self.label_team5.setFont(font)
        self.label_team5.setStyleSheet("QLabel {\n"
"min-width: 180px;;\n"
"min-height: 25px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 12px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"}")
        self.label_team5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team5.setObjectName("label_team5")
        self.verticalLayout_Character5.addWidget(self.label_team5, 0, QtCore.Qt.AlignHCenter)
        self.label_Image5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image5.setMinimumSize(QtCore.QSize(180, 180))
        self.label_Image5.setMaximumSize(QtCore.QSize(180, 180))
        self.label_Image5.setAutoFillBackground(False)
        self.label_Image5.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_Image5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Image5.setLineWidth(2)
        self.label_Image5.setText("")
        self.label_Image5.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.label_Image5.setScaledContents(True)
        self.label_Image5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image5.setObjectName("label_Image5")
        self.verticalLayout_Character5.addWidget(self.label_Image5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Name5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setPointSize(12)
        font.setBold(False)
        self.label_Name5.setFont(font)
        self.label_Name5.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_Name5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name5.setObjectName("label_Name5")
        self.verticalLayout_Character5.addWidget(self.label_Name5)
        self.pushButton_Select5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select5.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Fan Heiti Std")
        font.setPointSize(14)
        self.pushButton_Select5.setFont(font)
        self.pushButton_Select5.setStyleSheet("QPushButton {\n"
"border-radius: 11px;\n"
"color: #FFF;\n"
"background: rgb(34, 36, 44);\n"
"/*background-color: rgb(34, 36, 44);*/\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 3px solid rgb(118, 118, 118)\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(70, 80,87);\n"
"border: 3px solid rgb(200,200,200)\n"
"}")
        self.pushButton_Select5.setObjectName("pushButton_Select5")
        self.verticalLayout_Character5.addWidget(self.pushButton_Select5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_Row2.addLayout(self.verticalLayout_Character5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Row2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_Row2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_YourTeam = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nesatho")
        font.setBold(False)
        self.label_YourTeam.setFont(font)
        self.label_YourTeam.setStyleSheet("color : #000;\n"
"background: rgba(0, 0, 0, 0);")
        self.label_YourTeam.setObjectName("label_YourTeam")
        self.verticalLayout.addWidget(self.label_YourTeam, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.SelectedFormation = QtWidgets.QLabel(self.centralwidget)
        self.SelectedFormation.setMaximumSize(QtCore.QSize(90, 90))
        self.SelectedFormation.setText("")
        self.SelectedFormation.setPixmap(QtGui.QPixmap("../field.svg"))
        self.SelectedFormation.setScaledContents(True)
        self.SelectedFormation.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedFormation.setObjectName("SelectedFormation")
        self.horizontalLayout_3.addWidget(self.SelectedFormation, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SelectedCharacter01 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter01.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter01.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter01.setText("")
        self.SelectedCharacter01.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter01.setScaledContents(False)
        self.SelectedCharacter01.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter01.setObjectName("SelectedCharacter01")
        self.gridLayout.addWidget(self.SelectedCharacter01, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter04 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter04.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter04.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter04.setText("")
        self.SelectedCharacter04.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter04.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter04.setObjectName("SelectedCharacter04")
        self.gridLayout.addWidget(self.SelectedCharacter04, 1, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter09 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter09.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter09.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter09.setText("")
        self.SelectedCharacter09.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter09.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter09.setObjectName("SelectedCharacter09")
        self.gridLayout.addWidget(self.SelectedCharacter09, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter11 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter11.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter11.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter11.setText("")
        self.SelectedCharacter11.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter11.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter11.setObjectName("SelectedCharacter11")
        self.gridLayout.addWidget(self.SelectedCharacter11, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter13 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter13.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter13.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter13.setText("")
        self.SelectedCharacter13.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter13.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter13.setObjectName("SelectedCharacter13")
        self.gridLayout.addWidget(self.SelectedCharacter13, 2, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter07 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter07.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter07.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SelectedCharacter07.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter07.setText("")
        self.SelectedCharacter07.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter07.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter07.setObjectName("SelectedCharacter07")
        self.gridLayout.addWidget(self.SelectedCharacter07, 1, 8, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter16 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter16.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter16.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter16.setText("")
        self.SelectedCharacter16.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter16.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter16.setObjectName("SelectedCharacter16")
        self.gridLayout.addWidget(self.SelectedCharacter16, 2, 9, 1, 1, QtCore.Qt.AlignVCenter)
        self.SelectedCharacter06 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter06.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter06.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter06.setText("")
        self.SelectedCharacter06.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter06.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter06.setObjectName("SelectedCharacter06")
        self.gridLayout.addWidget(self.SelectedCharacter06, 1, 7, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter14 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter14.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter14.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter14.setText("")
        self.SelectedCharacter14.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter14.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter14.setObjectName("SelectedCharacter14")
        self.gridLayout.addWidget(self.SelectedCharacter14, 2, 7, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter15 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter15.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SelectedCharacter15.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter15.setText("")
        self.SelectedCharacter15.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter15.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter15.setObjectName("SelectedCharacter15")
        self.gridLayout.addWidget(self.SelectedCharacter15, 2, 8, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter03 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter03.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter03.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter03.setText("")
        self.SelectedCharacter03.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter03.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter03.setObjectName("SelectedCharacter03")
        self.gridLayout.addWidget(self.SelectedCharacter03, 1, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter08 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter08.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter08.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter08.setText("")
        self.SelectedCharacter08.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter08.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter08.setObjectName("SelectedCharacter08")
        self.gridLayout.addWidget(self.SelectedCharacter08, 1, 9, 1, 1, QtCore.Qt.AlignHCenter)
        self.SelectedCharacter12 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter12.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter12.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter12.setText("")
        self.SelectedCharacter12.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter12.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter12.setObjectName("SelectedCharacter12")
        self.gridLayout.addWidget(self.SelectedCharacter12, 2, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter05 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter05.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter05.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter05.setText("")
        self.SelectedCharacter05.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter05.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter05.setObjectName("SelectedCharacter05")
        self.gridLayout.addWidget(self.SelectedCharacter05, 1, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter10 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter10.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter10.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter10.setText("")
        self.SelectedCharacter10.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter10.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter10.setObjectName("SelectedCharacter10")
        self.gridLayout.addWidget(self.SelectedCharacter10, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.SelectedCharacter02 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter02.setMinimumSize(QtCore.QSize(50, 50))
        self.SelectedCharacter02.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCharacter02.setText("")
        self.SelectedCharacter02.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCharacter02.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCharacter02.setObjectName("SelectedCharacter02")
        self.gridLayout.addWidget(self.SelectedCharacter02, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.SelectedCoach = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCoach.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.SelectedCoach.setText("")
        self.SelectedCoach.setPixmap(QtGui.QPixmap("../character-placeholder.png"))
        self.SelectedCoach.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectedCoach.setObjectName("SelectedCoach")
        self.horizontalLayout_3.addWidget(self.SelectedCoach, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">Random Draft Inazuma Eleven</span></p></body></html>"))
        self.comboBox_Saison.setItemText(0, _translate("MainWindow", "Inazuma Eleven 1"))
        self.comboBox_Saison.setItemText(1, _translate("MainWindow", "Inazuma Eleven 2"))
        self.comboBox_Saison.setItemText(2, _translate("MainWindow", "Inazuma Eleven 3"))
        self.comboBox_Saison.setItemText(3, _translate("MainWindow", "Inazuma Eleven GO"))
        self.comboBox_Saison.setItemText(4, _translate("MainWindow", "Inazuma Eleven GO ChronoStone"))
        self.comboBox_Saison.setItemText(5, _translate("MainWindow", "Inazuma Eleven GO Galaxy"))
        self.comboBox_Saison.setItemText(6, _translate("MainWindow", "Inazuma Eleven Ares"))
        self.comboBox_Saison.setItemText(7, _translate("MainWindow", "Inazuma Eleven Orion"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Formation"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Gardien"))
        self.comboBox_type.setItemText(2, _translate("MainWindow", "Défenseur"))
        self.comboBox_type.setItemText(3, _translate("MainWindow", "Milieu"))
        self.comboBox_type.setItemText(4, _translate("MainWindow", "Attaquant"))
        self.comboBox_type.setItemText(5, _translate("MainWindow", "Coach"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start Random pick"))
        self.label_team1.setText(_translate("MainWindow", "Team 1"))
        self.label_Name1.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select1.setText(_translate("MainWindow", "Select"))
        self.label_team2.setText(_translate("MainWindow", "Team 2"))
        self.label_Name2.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select2.setText(_translate("MainWindow", "Select"))
        self.label_team3.setText(_translate("MainWindow", "Team 3"))
        self.label_Name3.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select3.setText(_translate("MainWindow", "Select"))
        self.label_team4.setText(_translate("MainWindow", "Team 4"))
        self.label_Name4.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select4.setText(_translate("MainWindow", "Select"))
        self.label_team5.setText(_translate("MainWindow", "Team 5"))
        self.label_Name5.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.pushButton_Select5.setText(_translate("MainWindow", "Select"))
        self.label_YourTeam.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Your Team</span></p></body></html>"))
import rsc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
