# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inazuma.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import random
import time
import re

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        self.Nb_Cycle = 4
        self.Countdown = 15
        
        self.yourTeam = []
        self.offset = 0
        self.counter = 0
        self.Status = False
        self.selected_previous_option = "Formation"

        self.Team = {
            "RM": "Raimon",
            "OC": "Occulte",
            "WD": "Wild",
            "CT": "Cybertech",
            "OK": "Otaku",
            "RA": "Royal Academie",
            "SK": "Shuriken",
            "TA": "Terria",
            "KW": "Kirkwood",
            "ZS": "Zeus",
            "OI": "Onze d'Inazuma",
            "SS": "Street Sally's",
            "KF": "Inazuma Kids FC",
            "UB": "Umbrella",

            "ST": "Services Secrets",
            "AP": "Alpin",
            "CD": "Cloître Divin",
            "3C": "Super Triple C",
            "FS": "Fauxshore",
            "MT": "Mary Times",
            "TG": "Tempête des Gémeaux",
            "EP": "Epsilon",
            "NE": "Nouvel Epsilon",
            "NR": "Nouvelle Royal Academie",
            "PM": "Prominence",
            "DD": "Diamond Dust",
            "GS": "Genesis",
            "EN": "Empereurs Noirs",
            "RdG": "Robots de Garde",
            "FT": "Forest Team",
            "JI": "Jeunes Inazuma",

            "IJ": "Inazuma Japon",
            "NJ": "Neo Japon",
            "BW": "Big Waves",
            "LD": "Lions du Désert",
            "DF": "Dragons de Feu",
            "KQ": "Knights of Queen",
            "TD": "Team D",
            "LE": "Les Empereurs",
            "LL": "Les Licornes",
            "OP": "Orphée",
            "RF": "Les Rois du Football",
            "TZ": "Team Zoolan",
            "LG": "Little Gigantes",
            "RG": "Rose Griffons",
            "TR": "Les Toreros Rouges",
            "BB": "Brocken Bogue",
            "CC": "The Cape Crusaders",
            "TO": "Team Ogre",
            "MC": "Sky Team",
            "DT": "Dark Team",
            "AN": "Anges Noirs",
            
            "AO": "l'Âge d'Or",
            "KFGO": "Inazuma KFC",
            "UMT": "Ultramégatétra",
            "RMGO": "Raimon GO",
            "RM R": "Raimon Reserve",
            "CN": "Chevaliers Noirs",
            "SR": "Surdoués",
            "VL": "Voie Lactée",
            "FTP": "Foi Toute-Puissante",
            "RAGO": "Royal Academy GO",
            "BP": "Baie des Pirates",
            "ML": "Mers Lunaires",
            "APGO": "Alpin GO",
            "KWGO": "Kirkwood GO",
            "CM": "Collège des Mirages",
            "CU": "Collège Universel",
            "MO": "Mont Olympe",
            "AdD": "Alliance du Dragon",
            "LME": "Lumière Éternelle",
            "OA": "Ombre Ancestral",
            "E0": "Équipe Zéro",
            "GdS": "Griffe du Sud",
            "CdN": "Croc du Nord",
            "RdD": "Rage du Démon",


            "SHW": "Les Sherwinds",
            "PO": "Protocol Omega",
            "PO2": "Protocol Omega 2.0",
            "PO3": "Protocol Omega 3.0",
            "ZD": "Zanark Domination",
            "EX": "Excellence",
            "ZAN": "Zan",
            "GIH": "Gihl",
            "GAH": "Gahl",
            "RGN": "Ragna",
            "CS": "Chrono Storm",
            "BCB": "Bande du Cerf Blanc",
            "RS": "Robots de Surveillance",
            "SA": "Statues d'Argile",
            "IJE": "Inazuma Japon Évolution",
            "RdD": "Roses du Désespoir",
            "ES": "Enfants Sauvages",
            "TN": "Traqueurs Nocturnes",

            "IN": "Inazuma National",
            "DFGO": "Dragons de Feu (GO)",
            "BWGO": "Big Waves (GO)",
            "SBA": "Sabres Arides",
            "TT": "Tigres de Thaïlande",
            "LO": "Loups d'Ouzbékistan",
            "OT": "Onze Terrestre",
            "OS": "Onze de Silica",
            "ON": "Onze de Naiadi",
            "OM": "Onze de Magmavia",
            "OF": "Onze de Fertilia",
            "FM": "Falam Medius",
            "AI": "Armada Ixar",
            "BIBG": "Big Bang",
            "SPNA": "Supernova",
            "TS": "Terrible Shadow",

            "IKRM": "Inakuni Raimon",
            "BT": "Bastion",
            "AS": "Anima Sana",
            "PS": "École Polaris",
            "AA": "École Alia",
            "LD": "Lambda",
            "SN": "Sélène",

            "RB": "Red Bison",
            "SHST": "Shining Satans",
            "ET": "Eternal Dancers",
            "PHoA": "Phoenix Army of Arab",
            "SAoA": "Soccer Acrobatic of Arab",
            "IG": "Invincible Giant",
            "SU": "Star Unicorn",
            "NI": "Navy Invaders",
            "PFS": "Perfect Spark",
            "OS": "Olé de Samba",
            "GQ": "Guardians of Queen",
            "SO": "Shadow of Orion"
            }

        self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs","Inazuma Eleven 1"))
        self.FolderPath2 = os.path.abspath(os.path.join(os.getcwd(), "Formation"))
        self.FolderPath3 = os.path.abspath(os.path.join(os.getcwd(), "Coach", "Inazuma Eleven 1"))

        self.Joueurs = [os.path.join(self.FolderPath, fichier) for fichier in os.listdir(self.FolderPath) if os.path.isfile(os.path.join(self.FolderPath, fichier)) and fichier.lower().endswith(".png")]
        # Initialiser les listes
        self.Formation = [os.path.join(self.FolderPath2, fichier) for fichier in os.listdir(self.FolderPath2) if os.path.isfile(os.path.join(self.FolderPath2, fichier)) and fichier.lower().endswith(".png")]
        self.FW = []
        self.GK = []
        self.MF = []
        self.DF = []
        self.Coach  = [os.path.join(self.FolderPath3, fichier) for fichier in os.listdir(self.FolderPath3) if os.path.isfile(os.path.join(self.FolderPath3, fichier)) and fichier.lower().endswith(".png")]

        self.CurrentList = self.Formation

        # Parcourir la liste des joueurs et les classer
        for joueur in self.Joueurs:
            # Extraire le nom de fichier
            nom_fichier = os.path.basename(joueur)

            # Vérifier la présence de chaque chaîne de caractères et classer le joueur en conséquence
            if "(FW)" in nom_fichier:
                self.FW.append(joueur)
            elif "(GK)" in nom_fichier:
                self.GK.append(joueur)
            elif "(MF)" in nom_fichier:
                self.MF.append(joueur)
            elif "(DF)" in nom_fichier:
                self.DF.append(joueur)
                
        ####################################################################
        ####################################################################
                
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setObjectName(u"line_5")
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setLineWidth(4)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.verticalLayout.addWidget(self.line_1)

        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout.addWidget(self.label_Title)
        #spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        #self.verticalLayout.addItem(spacerItem)

        self.comboBox_Saison = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Saison.setEditable(False)
        self.comboBox_Saison.setCurrentText("")
        self.comboBox_Saison.setPlaceholderText("")
        self.comboBox_Saison.setObjectName("comboBox_Saison")
        self.comboBox_Saison.addItem("Inazuma Eleven 1")
        self.comboBox_Saison.addItem("Inazuma Eleven 2")
        self.comboBox_Saison.addItem("Inazuma Eleven 3")
        self.comboBox_Saison.addItem("Inazuma Eleven GO")
        self.comboBox_Saison.addItem("Inazuma Eleven GO Chrono Stone")
        self.comboBox_Saison.addItem("Inazuma Eleven Go Galaxy")
        self.comboBox_Saison.addItem("Inazuma Eleven Ares")
        self.comboBox_Saison.addItem("Inazuma Eleven Orion")
        self.verticalLayout.addWidget(self.comboBox_Saison)

        self.comboBox_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type.setEditable(False)
        self.comboBox_type.setCurrentText("")
        self.comboBox_type.setPlaceholderText("")
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("Formation")
        self.comboBox_type.addItem("Gardien")
        self.comboBox_type.addItem("Défenseur")
        self.comboBox_type.addItem("Milieu")
        self.comboBox_type.addItem("Attaquant")
        self.comboBox_type.addItem("Coach")
        self.verticalLayout.addWidget(self.comboBox_type)
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.verticalLayout.addWidget(self.pushButton_Start)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_team1 = QtWidgets.QLabel(self.centralwidget)
        self.label_team1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team1.setObjectName("label_team1")
        self.verticalLayout_2.addWidget(self.label_team1)
        self.label_Image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image1.setMinimumSize(QtCore.QSize(170,170))
        self.label_Image1.setMaximumSize(QtCore.QSize(215,215))
        self.label_Image1.setText("")
        self.label_Image1.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image1.setScaledContents(True)
        self.label_Image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image1.setObjectName("label_Image1")
        self.verticalLayout_2.addWidget(self.label_Image1)
        self.label_Name1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Name1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name1.setObjectName("label_Name1")
        self.verticalLayout_2.addWidget(self.label_Name1)
        self.pushButton_Select1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select1.setObjectName("pushButton")
        self.pushButton_Select1.setEnabled(False)
        self.verticalLayout_2.addWidget(self.pushButton_Select1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_team2 = QtWidgets.QLabel(self.centralwidget)
        self.label_team2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team2.setObjectName("label_team2")
        self.verticalLayout_3.addWidget(self.label_team2)
        self.label_Image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image2.setMinimumSize(QtCore.QSize(170,170))
        self.label_Image2.setMaximumSize(QtCore.QSize(215,215))
        self.label_Image2.setText("")
        self.label_Image2.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image2.setScaledContents(True)
        self.label_Image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image2.setWordWrap(False)
        self.label_Image2.setObjectName("label_Image2")
        self.verticalLayout_3.addWidget(self.label_Image2)
        self.label_Name2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Name2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name2.setObjectName("label_Name2")
        self.verticalLayout_3.addWidget(self.label_Name2)
        self.pushButton_Select2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select2.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton_Select2)
        self.pushButton_Select2.setEnabled(False)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_team3 = QtWidgets.QLabel(self.centralwidget)
        self.label_team3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team3.setObjectName("label_team3")
        self.verticalLayout_4.addWidget(self.label_team3)
        self.label_Image3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image3.setMinimumSize(QtCore.QSize(170,170))
        self.label_Image3.setMaximumSize(QtCore.QSize(215,215))
        self.label_Image3.setText("")
        self.label_Image3.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image3.setScaledContents(True)
        self.label_Image3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image3.setObjectName("label_Image3")
        self.verticalLayout_4.addWidget(self.label_Image3)
        self.label_Name3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Name3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name3.setObjectName("label_Name3")
        self.verticalLayout_4.addWidget(self.label_Name3)
        self.pushButton_Select3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select3.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton_Select3)
        self.pushButton_Select3.setEnabled(False)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_team4 = QtWidgets.QLabel(self.centralwidget)
        self.label_team4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team4.setObjectName("label_team4")
        self.verticalLayout_5.addWidget(self.label_team4)
        self.label_Image4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image4.setMinimumSize(QtCore.QSize(170,170))
        self.label_Image4.setMaximumSize(QtCore.QSize(215,215))
        self.label_Image4.setText("")
        self.label_Image4.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image4.setScaledContents(True)
        self.label_Image4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image4.setObjectName("label_Image4")
        self.verticalLayout_5.addWidget(self.label_Image4)
        self.label_Name4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Name4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name4.setObjectName("label_Name4")
        self.verticalLayout_5.addWidget(self.label_Name4)
        self.pushButton_Select4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select4.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton_Select4)
        self.pushButton_Select4.setEnabled(False)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)

        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_team5 = QtWidgets.QLabel(self.centralwidget)
        self.label_team5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_team5.setObjectName("label_team5")
        self.verticalLayout_6.addWidget(self.label_team5)
        self.label_Image5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Image5.setMinimumSize(QtCore.QSize(170,170))
        self.label_Image5.setMaximumSize(QtCore.QSize(215,215))
        self.label_Image5.setText("")
        self.label_Image5.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image5.setScaledContents(True)
        self.label_Image5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image5.setObjectName("label_Image5")
        self.verticalLayout_6.addWidget(self.label_Image5)
        self.label_Name5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Name5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name5.setObjectName("label_Name5")
        self.verticalLayout_6.addWidget(self.label_Name5)
        self.pushButton_Select5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Select5.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton_Select5)
        self.pushButton_Select5.setEnabled(False)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        #spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        #self.verticalLayout.addItem(spacerItem6)



        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_5")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.verticalLayout.addWidget(self.line_2)

        self.label_YourTeam = QtWidgets.QLabel(self.centralwidget)
        self.label_YourTeam.setObjectName(u"label_YourTeam")
        self.verticalLayout.addWidget(self.label_YourTeam, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.SelectedFormation = QtWidgets.QLabel(self.centralwidget)
        self.SelectedFormation.setObjectName(u"SelectedFormation")
        self.SelectedFormation.setMaximumSize(QtCore.QSize(90, 90))
        self.SelectedFormation.setPixmap(QtGui.QPixmap(u"field.svg"))
        self.SelectedFormation.setScaledContents(True)
        self.horizontalLayout_3.addWidget(self.SelectedFormation)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SelectedCharacter1 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter1.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter1.setText("")
        self.SelectedCharacter1.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter1.setScaledContents(False)
        self.SelectedCharacter1.setObjectName("SelectedCharacter1")
        self.gridLayout.addWidget(self.SelectedCharacter1, 0, 2, 1, 1)
        self.SelectedCharacter2 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter2.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter2.setText("")
        self.SelectedCharacter2.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter2.setObjectName("SelectedCharacter2")
        self.gridLayout.addWidget(self.SelectedCharacter2, 0, 3, 1, 1)
        self.SelectedCharacter3 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter3.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter3.setText("")
        self.SelectedCharacter3.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter3.setObjectName("SelectedCharacter3")
        self.gridLayout.addWidget(self.SelectedCharacter3, 0, 4, 1, 1)
        self.SelectedCharacter4 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter4.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter4.setText("")
        self.SelectedCharacter4.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter4.setObjectName("SelectedCharacter4")
        self.gridLayout.addWidget(self.SelectedCharacter4, 0, 5, 1, 1)
        self.SelectedCharacter5 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter5.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter5.setText("")
        self.SelectedCharacter5.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter5.setObjectName("SelectedCharacter5")
        self.gridLayout.addWidget(self.SelectedCharacter5, 0, 6, 1, 1)
        self.SelectedCharacter6 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter6.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter6.setText("")
        self.SelectedCharacter6.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter6.setObjectName("SelectedCharacter6")
        self.gridLayout.addWidget(self.SelectedCharacter6, 0, 7, 1, 1)
        self.SelectedCharacter7 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter7.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter7.setText("")
        self.SelectedCharacter7.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter7.setObjectName("SelectedCharacter7")
        self.gridLayout.addWidget(self.SelectedCharacter7, 0, 8, 1, 1)
        self.SelectedCharacter8 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter8.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter8.setText("")
        self.SelectedCharacter8.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter8.setObjectName("SelectedCharacter8")
        self.gridLayout.addWidget(self.SelectedCharacter8, 0, 9, 1, 1)
        self.SelectedCharacter9 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter9.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter9.setText("")
        self.SelectedCharacter9.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter9.setObjectName("SelectedCharacter9")
        self.gridLayout.addWidget(self.SelectedCharacter9, 1, 2, 1, 1)
        self.SelectedCharacter10 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter10.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter10.setText("")
        self.SelectedCharacter10.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter10.setObjectName("SelectedCharacter10")
        self.gridLayout.addWidget(self.SelectedCharacter10, 1, 3, 1, 1)
        self.SelectedCharacter11 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter11.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter11.setText("")
        self.SelectedCharacter11.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter11.setObjectName("SelectedCharacter11")
        self.gridLayout.addWidget(self.SelectedCharacter11, 1, 4, 1, 1)
        self.SelectedCharacter12 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter12.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter12.setText("")
        self.SelectedCharacter12.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter12.setObjectName("SelectedCharacter12")
        self.gridLayout.addWidget(self.SelectedCharacter12, 1, 5, 1, 1)
        self.SelectedCharacter13 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter13.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter13.setText("")
        self.SelectedCharacter13.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter13.setObjectName("SelectedCharacter13")
        self.gridLayout.addWidget(self.SelectedCharacter13, 1, 6, 1, 1)
        self.SelectedCharacter14 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter14.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter14.setText("")
        self.SelectedCharacter14.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter14.setObjectName("SelectedCharacter14")
        self.gridLayout.addWidget(self.SelectedCharacter14, 1, 7, 1, 1)
        self.SelectedCharacter15 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter15.setMinimumSize(QtCore.QSize(45, 45))
        self.SelectedCharacter15.setText("")
        self.SelectedCharacter15.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter15.setObjectName("SelectedCharacter15")
        self.gridLayout.addWidget(self.SelectedCharacter15, 1, 8, 1, 1)
        self.SelectedCharacter16 = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCharacter16.setMinimumSize(QtCore.QSize(45,45))
        self.SelectedCharacter16.setText("")
        self.SelectedCharacter16.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.SelectedCharacter16.setObjectName("SelectedCharacter16")
        self.gridLayout.addWidget(self.SelectedCharacter16, 1, 9, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)

        self.SelectedCoach = QtWidgets.QLabel(self.centralwidget)
        self.SelectedCoach.setObjectName(u"SelectedCoach")
        self.SelectedCoach.setPixmap(QtGui.QPixmap(u"character-placeholder.png"))
        self.horizontalLayout_3.addWidget(self.SelectedCoach)

        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        
        
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_5")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.verticalLayout.addWidget(self.line_3)

        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)

    


        ###################################################################################
        ###################################################################################
        ###################################################################################
        self.label_Image4.hide()
        self.label_Name4.hide()
        self.label_team4.hide()
        self.label_Image5.hide()
        self.label_Name5.hide()
        self.label_team5.hide()
        self.pushButton_Select4.hide()
        self.pushButton_Select5.hide()

        self.pushButton_Start.clicked.connect(self.StartRandomisation) 
        self.comboBox_type.currentIndexChanged.connect(self.on_comboBox_type_changed)
        self.comboBox_Saison.currentIndexChanged.connect(self.on_comboBox_Saison_changed)

        self.pushButton_Select1.clicked.connect(self.pushButton_Select1_clicked)
        self.pushButton_Select2.clicked.connect(self.pushButton_Select2_clicked)
        self.pushButton_Select3.clicked.connect(self.pushButton_Select3_clicked)
        self.pushButton_Select4.clicked.connect(self.pushButton_Select4_clicked)
        self.pushButton_Select5.clicked.connect(self.pushButton_Select5_clicked)

        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Random Draft Inazuma Eleven</span></p></body></html>"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start Random pick"))
        self.pushButton_Select1.setText(_translate("MainWindow", "Select"))
        self.pushButton_Select2.setText(_translate("MainWindow", "Select"))
        self.pushButton_Select3.setText(_translate("MainWindow", "Select"))
        self.pushButton_Select4.setText(_translate("MainWindow", "Select"))
        self.pushButton_Select5.setText(_translate("MainWindow", "Select"))
        self.label_team1.setText(_translate("MainWindow", "Team 1"))
        self.label_Name1.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.label_team2.setText(_translate("MainWindow", "Team 2"))
        self.label_Name2.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.label_team3.setText(_translate("MainWindow", "Team 3"))
        self.label_Name3.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.label_team4.setText(_translate("MainWindow", "Team 4"))
        self.label_Name4.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.label_team5.setText(_translate("MainWindow", "Team 5"))
        self.label_Name5.setText(_translate("MainWindow", "Prénom Nom - Genre"))
        self.label_YourTeam.setText(_translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Your Team</span></p></body></html>", None))
        self.SelectedCharacter1.setText("")
        self.SelectedCharacter2.setText("")
        self.SelectedCharacter3.setText("")
        self.SelectedCharacter4.setText("")
        self.SelectedCharacter5.setText("")
        self.SelectedCharacter6.setText("")
        self.SelectedCharacter7.setText("")
        self.SelectedCharacter8.setText("")
        self.SelectedCharacter9.setText("")
        self.SelectedCharacter10.setText("")
        self.SelectedCharacter11.setText("")
        self.SelectedCharacter12.setText("")
        self.SelectedCharacter13.setText("")
        self.SelectedCharacter14.setText("")
        self.SelectedCharacter15.setText("")
        self.SelectedCharacter16.setText("")


    def on_comboBox_Saison_changed(self, index):
        # Fonction appelée lorsque la sélection de la combo box change
        selected_option = self.comboBox_Saison.currentText()
        
        if selected_option == "Inazuma Eleven 1":
            self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven 1"))
        if selected_option == "Inazuma Eleven 2":
            self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven 2"))
        if selected_option == "Inazuma Eleven 3":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven 3"))
        if selected_option == "Inazuma Eleven GO":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven GO"))
        if selected_option == "Inazuma Eleven GO Chrono Stone":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven GO Chrono Stone"))
        if selected_option == "Inazuma Eleven Go Galaxy":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven Go Galaxy"))
        if selected_option == "Inazuma Eleven Ares":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven Ares"))
        if selected_option == "Inazuma Eleven Orion":
           self.FolderPath = os.path.abspath(os.path.join(os.getcwd(), "Joueurs", "Inazuma Eleven Orion"))



        self.Joueurs = [os.path.join(self.FolderPath, fichier) for fichier in os.listdir(self.FolderPath) if os.path.isfile(os.path.join(self.FolderPath, fichier)) and fichier.lower().endswith(".png")]
        # Initialiser les listes
        self.FW = []
        self.GK = []
        self.MF = []
        self.DF = []
        self.on_comboBox_type_changed(index = 0)

        # Parcourir la liste des joueurs et les classer
        for joueur in self.Joueurs:
            # Extraire le nom de fichier
            nom_fichier = os.path.basename(joueur)

            # Vérifier la présence de chaque chaîne de caractères et classer le joueur en conséquence
            if "(FW)" in nom_fichier:
                self.FW.append(joueur)
            elif "(GK)" in nom_fichier:
                self.GK.append(joueur)
            elif "(MF)" in nom_fichier:
                self.MF.append(joueur)
            elif "(DF)" in nom_fichier:
                self.DF.append(joueur)

    def on_comboBox_type_changed(self, index):
        _translate = QtCore.QCoreApplication.translate
        # Fonction appelée lorsque la sélection de la combo box change
        selected_option = self.comboBox_type.currentText()
        self.Status = False

        FolderPathCoach = os.path.abspath(os.path.join(os.getcwd(), "Coach", self.comboBox_Saison.currentText()))
        
        if self.selected_previous_option == "Coach" or self.selected_previous_option == "Formation":
            self.label_Image4.show()
            self.label_Name4.show()
            self.label_team4.show()
            self.label_Image5.show()
            self.label_Name5.show()
            self.label_team5.show()
            self.pushButton_Select4.show()
            self.pushButton_Select5.show()
            self.label_Image4.setPixmap(QtGui.QPixmap("character-placeholder.png"))
            self.label_Image5.setPixmap(QtGui.QPixmap("character-placeholder.png"))        
            self.label_team4.setText(_translate("MainWindow", "Team 4"))
            self.label_Name4.setText(_translate("MainWindow", "Prénom Nom - Genre"))
            self.label_team5.setText(_translate("MainWindow", "Team 5"))
            self.label_Name5.setText(_translate("MainWindow", "Prénom Nom - Genre"))
            self.pushButton_Select4.setEnabled(False)
            self.pushButton_Select5.setEnabled(False)

        if selected_option == "Formation":
            self.CurrentList = self.Formation
            self.label_Image4.hide()
            self.label_Name4.hide()
            self.label_team4.hide()
            self.label_Image5.hide()
            self.label_Name5.hide()
            self.label_team5.hide()
            self.pushButton_Select4.hide()
            self.pushButton_Select5.hide()
            self.Status = True
        if selected_option == "Coach":
            self.CurrentList = [os.path.join(FolderPathCoach, fichier) for fichier in os.listdir(FolderPathCoach) if os.path.isfile(os.path.join(FolderPathCoach, fichier)) and fichier.lower().endswith(".png")]
            self.label_Image4.hide()
            self.label_Name4.hide()
            self.label_team4.hide()
            self.label_Image5.hide()
            self.label_Name5.hide()
            self.label_team5.hide()
            self.pushButton_Select4.hide()
            self.pushButton_Select5.hide()
            self.Status = True       
        if selected_option == "Gardien":
            self.CurrentList = self.GK
            self.Status = True
        if selected_option == "Défenseur":
            self.CurrentList = self.DF
            self.Status = True
        if selected_option == "Milieu":
            self.CurrentList = self.MF
            self.Status = True
        if selected_option == "Attaquant":
            self.CurrentList = self.FW
            self.Status = True

        self.selected_previous_option = selected_option

    def selectedCharacter(self,pathPerso):
        if self.comboBox_type.currentText() == "Formation":
            self.SelectedFormation.setPixmap(QtGui.QPixmap(pathPerso))
            return
        
        if self.comboBox_type.currentText() == "Coach":
            self.SelectedCoach.setPixmap(QtGui.QPixmap(pathPerso))
            return
        
        if self.Status == True:
            self.counter += 1

            if self.counter == 1:
                self.SelectedCharacter1.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 2:
                self.SelectedCharacter2.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 3:
                self.SelectedCharacter3.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 4:
                self.SelectedCharacter4.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 5:
                self.SelectedCharacter5.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 6:
                self.SelectedCharacter6.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 7:
                self.SelectedCharacter7.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 8:
                self.SelectedCharacter8.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 9:
                self.SelectedCharacter9.setPixmap(QtGui.QPixmap(pathPerso))
            
            if self.counter == 10:
                self.SelectedCharacter10.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 11:
                self.SelectedCharacter11.setPixmap(QtGui.QPixmap(pathPerso))
                
            if self.counter == 12:
                self.SelectedCharacter12.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 13:
                self.SelectedCharacter13.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 14:
                self.SelectedCharacter14.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 15:
                self.SelectedCharacter15.setPixmap(QtGui.QPixmap(pathPerso))

            if self.counter == 16:
                self.SelectedCharacter16.setPixmap(QtGui.QPixmap(pathPerso))

        return

    def pushButton_Select1_clicked(self):
        self.selectedCharacter(self.CurrentList[-5])
        self.yourTeam.append(self.CurrentList[-5])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-5+self.offset] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-5])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-5])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-5])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-5])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-5])
        
        self.label_Image2.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("character-placeholder.png"))

    def pushButton_Select2_clicked(self):
        self.selectedCharacter(self.CurrentList[-4])
        self.yourTeam.append(self.CurrentList[-4])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-4] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-4])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-4])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-4])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-4])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-4])

        self.label_Image1.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("character-placeholder.png"))

    def pushButton_Select3_clicked(self):
        self.selectedCharacter(self.CurrentList[-3])
        self.yourTeam.append(self.CurrentList[-3])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-3] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-3])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-3])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-3])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-3])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-3])

        self.label_Image1.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image2.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("character-placeholder.png"))

    def pushButton_Select4_clicked(self):
        self.selectedCharacter(self.CurrentList[-2])
        self.yourTeam.append(self.CurrentList[-2])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-2] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-2])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-2])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-2])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-2])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-2])

        self.label_Image1.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image2.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image5.setPixmap(QtGui.QPixmap("character-placeholder.png"))

    def pushButton_Select5_clicked(self):
        self.selectedCharacter(self.CurrentList[-1])
        self.yourTeam.append(self.CurrentList[-1])
        self.offset +=1
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        if self.CurrentList[-1] in self.CurrentList:
            self.CurrentList.remove(self.CurrentList[-1])

        if self.BaseNom in self.GK:
            self.GK.remove(self.CurrentList[-1])

        if self.BaseNom in self.DF:
            self.DF.remove(self.CurrentList[-1])
            
        if self.BaseNom in self.MF:
            self.MF.remove(self.CurrentList[-1])
            
        if self.BaseNom in self.FW:
            self.FW.remove(self.CurrentList[-1])

        self.label_Image1.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image2.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image3.setPixmap(QtGui.QPixmap("character-placeholder.png"))
        self.label_Image4.setPixmap(QtGui.QPixmap("character-placeholder.png"))


    def StartRandomisation(self):
        self.offset = 0
        self.pushButton_Start.setEnabled(False)
        self.pushButton_Select1.setEnabled(False)
        self.pushButton_Select2.setEnabled(False)
        self.pushButton_Select3.setEnabled(False)
        self.pushButton_Select4.setEnabled(False)
        self.pushButton_Select5.setEnabled(False)
        _translate = QtCore.QCoreApplication.translate

        # Parcourez la liste des joueurs et mettez à jour les images des labels
        
        self.TotalItems = self.Nb_Cycle * len(self.CurrentList)  # Total des éléments à travers toutes les boucles

        for j in range(self.Nb_Cycle):
            random.shuffle(self.CurrentList)
            for i, self.BaseNom in enumerate(self.CurrentList):
                #print(self.BaseNom)

                # Choisissez le label en fonction de l'index
                if i % 5 == 0:
                    label = self.label_Image1
                    label2 = self.label_Name1
                    label3 = self.label_team1
                elif i % 5 == 1:
                    label = self.label_Image2
                    label2 = self.label_Name2
                    label3 = self.label_team2
                elif i % 5 == 2:
                    label = self.label_Image3
                    label2 = self.label_Name3
                    label3 = self.label_team3
                elif i % 5 == 3:
                    label = self.label_Image4
                    label2 = self.label_Name4
                    label3 = self.label_team4
                else:
                    label = self.label_Image5
                    label2 = self.label_Name5
                    label3 = self.label_team5

                nom_fichier = os.path.basename(self.BaseNom)

                # Définir une expression régulière pour extraire le prénom, le nom et le genre
                if self.comboBox_type.currentText()== "Formation":
                    # Expression régulière
                    pattern = re.compile(r'\((.*?)\) (.+?)\.png')
                    nom_fichier1 = os.path.basename(self.CurrentList[-5])
                    match1 = pattern.match(nom_fichier1)
                    # Effectuer la correspondance avec le nom du fichier
                    match = pattern.match(nom_fichier)
                    # Extraire le prénom, le nom et le genre à partir des groupes capturants
                    team = match.group(1)
                    prenom_nom = match.group(2)
                    # Mettez à jour l'image du label
                    label2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                    label.setPixmap(QtGui.QPixmap(self.BaseNom))
                    label3.setText(_translate("MainWindow", "{}".format(team)))
                elif self.comboBox_type.currentText() == "Coach":
                    # Expression régulière
                    pattern = re.compile(r'\((.*?)\) (.+?)\.png')            
                    # Effectuer la correspondance avec le nom du fichier
                    match = pattern.match(nom_fichier)
                    # Extraire le prénom, le nom et le genre à partir des groupes capturants
                    team = match.group(1)
                    prenom_nom = match.group(2)
                    # Mettez à jour l'image du label
                    label2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                    label.setPixmap(QtGui.QPixmap(self.BaseNom))
                    label3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))
                else:
                    pattern = re.compile(r'\((.*?)\) \((.*?)\) \((.*?)\) (.+?)\.png')
                    match = pattern.match(nom_fichier)
                    # Extraire le prénom, le nom et le genre à partir des groupes capturants
                    team = match.group(1)
                    genre = match.group(3)
                    prenom_nom = match.group(4)
                    # Mettez à jour l'image du label
                    label2.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                    label.setPixmap(QtGui.QPixmap(self.BaseNom))
                    label3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

                progress_percentage = (i + len(self.CurrentList) * j) / self.TotalItems

                if progress_percentage < 0.6:
                    delay_factor = 0.1  # Vitesse rapide pour les 70% premiers
                elif progress_percentage < 0.7:
                    delay_factor = 0.3  # Ralentissement progressif pour les 20% suivants
                else:
                    delay_factor = 1000000  # Très lent pour les 10% derniers
                delay = 1/(1 + (self.TotalItems - i - len(self.CurrentList) * j) / delay_factor)

                # Convertir le délai de secondes à millisecondes
                delay_ms = delay /1000

                # Actualisez l'affichage à chaque itération
                print(f"Iteration {1 + (self.TotalItems - i - len(self.CurrentList) * j)}/{(len(self.CurrentList)*self.Nb_Cycle)}, Delay: {delay_ms} ms\t",delay_factor)
                time.sleep(delay_ms)
                QtWidgets.QApplication.processEvents()
        

        if self.comboBox_type.currentText()== "Formation":
            nom_fichier1 = os.path.basename(self.CurrentList[-5])
            match1 = pattern.match(nom_fichier1)
            if match1:
                team = match1.group(1)
                prenom_nom = match1.group(2)
                self.label_Name1.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team1.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier2 = os.path.basename(self.CurrentList[-4])
            match2 = pattern.match(nom_fichier2)
            if match2:
                team = match2.group(1)
                prenom_nom = match2.group(2)
                self.label_Name2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team2.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier3 = os.path.basename(self.CurrentList[-3])
            match3 = pattern.match(nom_fichier3)
            if match3:
                team = match3.group(1)
                prenom_nom = match3.group(2)
                self.label_Name3.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team3.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier4 = os.path.basename(self.CurrentList[-2])
            match4 = pattern.match(nom_fichier4)
            if match4:
                team = match4.group(1)
                prenom_nom = match4.group(2)
                self.label_Name4.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team4.setText(_translate("MainWindow", "{}".format(team)))

            nom_fichier5 = os.path.basename(self.CurrentList[-1])
            match5 = pattern.match(nom_fichier5)
            if match5:
                team = match5.group(1)
                prenom_nom = match5.group(2)
                self.label_Name5.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team5.setText(_translate("MainWindow", "{}".format(team)))

        elif self.comboBox_type.currentText() == "Coach":
            nom_fichier1 = os.path.basename(self.CurrentList[-5])
            match1 = pattern.match(nom_fichier1)
            if match1:
                team = match1.group(1)
                prenom_nom = match1.group(2)
                self.label_Name1.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team1.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier2 = os.path.basename(self.CurrentList[-4])
            match2 = pattern.match(nom_fichier2)
            if match2:
                team = match2.group(1)
                prenom_nom = match2.group(2)
                self.label_Name2.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team2.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier3 = os.path.basename(self.CurrentList[-3])
            match3 = pattern.match(nom_fichier3)
            if match3:
                team = match3.group(1)
                prenom_nom = match3.group(2)
                self.label_Name3.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier4 = os.path.basename(self.CurrentList[-2])
            match4 = pattern.match(nom_fichier4)
            if match4:
                team = match4.group(1)
                prenom_nom = match4.group(2)
                self.label_Name4.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team4.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier5 = os.path.basename(self.CurrentList[-1])
            match5 = pattern.match(nom_fichier5)
            if match5:
                team = match5.group(1)
                prenom_nom = match5.group(2)
                self.label_Name5.setText(_translate("MainWindow", "{}".format(prenom_nom)))
                self.label_team5.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))
        else:
            nom_fichier1 = os.path.basename(self.CurrentList[-5])
            match1 = pattern.match(nom_fichier1)
            if match1:
                team = match1.group(1)
                genre = match1.group(3)
                prenom_nom = match1.group(4)
                self.label_Name1.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team1.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier2 = os.path.basename(self.CurrentList[-4])
            match2 = pattern.match(nom_fichier2)
            if match2:
                team = match2.group(1)
                genre = match2.group(3)
                prenom_nom = match2.group(4)
                self.label_Name2.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team2.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier3 = os.path.basename(self.CurrentList[-3])
            match3 = pattern.match(nom_fichier3)
            if match3:
                team = match3.group(1)
                genre = match3.group(3)
                prenom_nom = match3.group(4)
                self.label_Name3.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team3.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier4 = os.path.basename(self.CurrentList[-2])
            match4 = pattern.match(nom_fichier4)
            if match4:
                team = match4.group(1)
                genre = match4.group(3)
                prenom_nom = match4.group(4)
                self.label_Name4.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team4.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))

            nom_fichier5 = os.path.basename(self.CurrentList[-1])
            match5 = pattern.match(nom_fichier5)
            if match5:
                team = match5.group(1)
                genre = match5.group(3)
                prenom_nom = match5.group(4)
                self.label_Name5.setText(_translate("MainWindow", "{} - {}".format(prenom_nom,genre)))
                self.label_team5.setText(_translate("MainWindow", "{}".format(self.Team.get(team))))


        self.label_Image1.setPixmap(QtGui.QPixmap(self.CurrentList[-5]))
        self.label_Image2.setPixmap(QtGui.QPixmap(self.CurrentList[-4]))
        self.label_Image3.setPixmap(QtGui.QPixmap(self.CurrentList[-3]))
        self.label_Image4.setPixmap(QtGui.QPixmap(self.CurrentList[-2]))
        self.label_Image5.setPixmap(QtGui.QPixmap(self.CurrentList[-1]))
                
        self.pushButton_Start.setEnabled(True)
        self.pushButton_Select1.setEnabled(True)
        self.pushButton_Select2.setEnabled(True)
        self.pushButton_Select3.setEnabled(True)
        self.pushButton_Select4.setEnabled(True)
        self.pushButton_Select5.setEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


